import { useState } from 'react';
import { MessageSquareText, Send } from 'lucide-react';
import { useFlow } from '../context/FlowContext';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { EmptyState } from '../components/ui/EmptyState';

export function Messages() {
  const { conversations, setConversations } = useFlow(); const [active, setActive] = useState(conversations[0]?.id); const [text, setText] = useState(''); const c = conversations.find(x => x.id === active);
  const send = () => { if (!text.trim() || !c) return; setConversations(prev => prev.map(conv => conv.id === c.id ? { ...conv, last: text, messages: [...conv.messages, { id: crypto.randomUUID(), sender: 'Alex', body: text, time: 'Now', mine: true }] } : conv)); setText(''); };
  if (conversations.length === 0) return <EmptyState icon={MessageSquareText} title="No messages" body="Start a conversation with your team." action="New message"/>;
  return <div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[340px_1fr]"><aside className="surface-card rounded-2xl p-4"><h2 className="text-2xl font-semibold">Messages</h2><Input className="mt-4" placeholder="Search conversations"/><div className="mt-4 space-y-2">{conversations.map(conv => <button key={conv.id} onClick={() => setActive(conv.id)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left transition ${conv.id === active ? 'bg-flow-500/10' : 'hover:bg-black/5 dark:hover:bg-white/10'}`}><div className="relative grid h-10 w-10 place-items-center rounded-full bg-slate-900 text-white dark:bg-white dark:text-slate-950">{conv.avatar}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[rgb(var(--surface))] ${conv.online ? 'bg-emerald-500' : 'bg-slate-400'}`}/></div><div className="min-w-0"><p className="font-medium">{conv.name}</p><p className="truncate text-sm text-muted">{conv.last}</p></div></button>)}</div></aside><section className="surface-card flex min-h-[70vh] flex-col rounded-2xl"><header className="border-b border-[rgb(var(--border))] p-5"><h3 className="font-semibold">{c?.name}</h3><p className="text-sm text-muted">{c?.online ? 'Online' : 'Away'}</p></header><div className="flex-1 space-y-3 p-5">{c?.messages.map(m => <div key={m.id} className={`flex ${m.mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-md rounded-2xl px-4 py-2 ${m.mine ? 'brand-gradient text-white' : 'bg-[rgb(var(--bg-soft))]'}`}><p className="text-sm">{m.body}</p><p className="mt-1 text-xs opacity-70">{m.time}</p></div></div>)}</div><div className="flex gap-2 border-t border-[rgb(var(--border))] p-4"><Input value={text} onChange={e => setText(e.target.value)} onKeyDown={e => e.key === 'Enter' && send()} placeholder="Write a message..."/><Button variant="primary" onClick={send}><Send size={16}/></Button></div></section></div>;
}
