import { useState } from 'react';
import { Shield, SlidersHorizontal } from 'lucide-react';
import { Tabs } from '../components/ui/Tabs';
import { Card } from '../components/ui/Card';
import { Input } from '../components/ui/Input';
import { Select } from '../components/ui/Select';
import { Button } from '../components/ui/Button';

const tabs = ['Profile','Account','Appearance','Notifications','Security','Team','Billing','Integrations'] as const;
export function Settings() {
  const [tab, setTab] = useState<(typeof tabs)[number]>('Profile'); const [saved, setSaved] = useState(false);
  return <div className="mx-auto max-w-5xl space-y-6"><div><h2 className="text-3xl font-semibold tracking-tight">Settings</h2><p className="text-muted">Configure your workspace, preferences, and connected tools.</p></div><Tabs tabs={[...tabs]} value={tab} onChange={setTab}/><Card><div className="mb-5 flex items-center gap-3"><SlidersHorizontal className="text-flow-600"/><h3 className="text-lg font-semibold">{tab}</h3></div>{tab === 'Profile' && <div className="grid gap-3 md:grid-cols-2"><Input defaultValue="Alex Morgan"/><Input defaultValue="alex@flow.test"/><Input className="md:col-span-2" defaultValue="Product Lead focused on elegant team productivity."/></div>}{tab === 'Account' && <div className="grid gap-3 md:grid-cols-2"><Select defaultValue="UTC-05"><option>UTC-05</option><option>UTC+00</option></Select><Select defaultValue="English"><option>English</option><option>Spanish</option></Select></div>}{tab === 'Appearance' && <div className="grid gap-3 md:grid-cols-2"><Select defaultValue="System"><option>System</option><option>Light</option><option>Dark</option></Select><Select defaultValue="Comfortable"><option>Comfortable</option><option>Compact</option></Select></div>}{tab === 'Notifications' && <div className="space-y-3">{['Task updates','Project changes','Mentions','Deadline reminders'].map(x => <label key={x} className="flex items-center justify-between rounded-xl border border-[rgb(var(--border))] p-3"><span>{x}</span><input type="checkbox" defaultChecked/></label>)}</div>}{tab === 'Security' && <div className="space-y-3"><div className="flex items-center gap-3 rounded-xl border border-[rgb(var(--border))] p-4"><Shield/><div><p className="font-medium">Two-factor authentication</p><p className="text-sm text-muted">Add an extra layer of account protection.</p></div><Button className="ml-auto">Enable</Button></div></div>}{['Team','Billing','Integrations'].includes(tab) && <div className="rounded-xl border border-[rgb(var(--border))] p-5"><p className="font-medium">{tab} controls</p><p className="mt-1 text-sm text-muted">Frontend controls are ready for future backend integration.</p><Button className="mt-4">Configure</Button></div>}<div className="mt-6 flex items-center gap-3"><Button variant="primary" onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1500); }}>Save changes</Button>{saved && <span className="text-sm text-emerald-600">Saved</span>}</div></Card></div>;
}
