import { UsersRound } from 'lucide-react';
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';
import { useFlow } from '../context/FlowContext';
import { Card } from '../components/ui/Card';
import { ProgressBar } from '../components/ui/ProgressBar';
import { EmptyState } from '../components/ui/EmptyState';

export function Team() {
  const { team, tasks } = useFlow();
  return <div className="mx-auto max-w-7xl space-y-6"><div><h2 className="text-3xl font-semibold tracking-tight">Team</h2><p className="text-muted">People, activity, ownership, and delivery health.</p></div>{team.length === 0 ? <EmptyState icon={UsersRound} title="No team members" body="Invite people to collaborate in Flow." action="Invite member"/> : <><section className="grid gap-4 md:grid-cols-3"><Card><p className="text-sm text-muted">Average productivity</p><p className="mt-2 text-3xl font-semibold">83%</p></Card><Card><p className="text-sm text-muted">Assigned tasks</p><p className="mt-2 text-3xl font-semibold">{tasks.length}</p></Card><Card><p className="text-sm text-muted">Online now</p><p className="mt-2 text-3xl font-semibold">{team.filter(m => m.online).length}</p></Card></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{team.map(member => <Card key={member.id}><div className="flex items-center gap-3"><div className="relative grid h-12 w-12 place-items-center rounded-full bg-slate-900 font-semibold text-white dark:bg-white dark:text-slate-950">{member.avatar}<span className={`absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-[rgb(var(--surface))] ${member.online ? 'bg-emerald-500' : 'bg-slate-400'}`}/></div><div><h3 className="font-semibold">{member.name}</h3><p className="text-sm text-muted">{member.role}</p></div></div><p className="mt-4 text-sm text-muted">{member.activity}</p><div className="mt-4 space-y-3"><div><div className="mb-1 flex justify-between text-sm"><span>Productivity</span><span>{member.productivity}%</span></div><ProgressBar value={member.productivity}/></div><div><div className="mb-1 flex justify-between text-sm"><span>Completion</span><span>{member.completion}%</span></div><ProgressBar value={member.completion}/></div></div><p className="mt-4 text-sm text-muted">Assigned tasks: {tasks.filter(t => t.assignee === member.id).length}</p></Card>)}</section><Card><h3 className="mb-4 text-lg font-semibold">Team analytics</h3><div className="h-72"><ResponsiveContainer><BarChart data={team}><XAxis dataKey="avatar" tick={{ fill: 'rgb(var(--muted))' }}/><Tooltip contentStyle={{ background: 'rgb(var(--surface))', border: '1px solid rgb(var(--border))', borderRadius: 12 }}/><Bar dataKey="productivity" fill="rgb(var(--brand))" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></Card></>}</div>;
}
